import TwSizeIndicator from "@/components/tw-size-indicator";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../style/main.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
  manifest: "/site.webmanifest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <TwSizeIndicator />
        {children}
      </body>
    </html>
  );
}
